### ISSUE TITLE
The front page carousel's third item is out of date.

### ISSUE THREAD

**Issue by dcporter** [sproutcore/website#14]
WWDC 2011. I assume we don't need four things in the carousel so this should be a simple excision.

**Comment by dcporter** [comment]
Oops, duplicate

**Comment by dcporter** [comment]
Oops, not duplicate!

**Comment by topherfangio** [comment]
Dang! Didn't see this issue first. Closed by https://github.com/sproutcore/website/commit/28edbc8c37dbfb80aa4d10dc9d9ab2fd3546e955
