### ISSUE TITLE
Copyright is out of date and owned by a dead company.

### ISSUE THREAD

**Issue by dcporter** [sproutcore/website#15]
Let's just remove the notice (see comment below).

**Comment by topherfangio** [comment]
I can definitely update the year, but I have no idea who owns
it...Copyright SproutCore?

## 

Topher Fangio

Director of Software Development
Pharos Resources

office: 325.216.2908
mobile: 325.660.7141

**Comment by dcporter** [comment]
According to Tyler, there is no longer a copyright owner. The site is MIT-licensed anyway, so we're in the clear as far as that goes, and since we're probably not going to get into the business of copyright enforcement, it probably makes sense to remove the copyright notice entirely.

**Comment by topherfangio** [comment]
Roger, will do.

## 

Topher Fangio

Director of Software Development
Pharos Resources

office: 325.216.2908
mobile: 325.660.7141
