### ISSUE TITLE
"SproutCore Bash 2011" banner should be removed from blog sidebar.

### ISSUE THREAD

**Issue by dcporter** [sproutcore/website#17]
It's a bit out of date.

**Comment by topherfangio** [comment]
I am removing this from the scrolling banner on the main page, however, I think the blog is separate. I don't see any blog posts within the "website" repo.

@publickeating - Can you shed any light on this request?

**Comment by dcporter** [comment]
Good call Topher, I bet this one is a WordPress thing. @publickeating I don't see any sidebar options in the admin panel, would you take a look at this or bump my permissions?

**Comment by dcporter** [comment]
Thanks @publickeating!
