### ISSUE TITLE
Confirm existing/add new consulting companies to the Contact Us tab.

### ISSUE THREAD

**Issue by topherfangio** [sproutcore/website#20]
The [Contact Us](http://sproutcore.com/about/#tab=contact-us-tab) tab currently has three consulting companies listed, and I'm only about 75% sure that 1 of them is actually still doing consulting.

Can we confirm which ones are doing it and add any new ones?

Once I have an official company, I'm happy to add it to the page as well.

**Comment by dcporter** [comment]
Fixed this in the apparently-as-yet-unpublished b74c378184fb33d61edc7e4222818335cc7433e7.

**Comment by topherfangio** [comment]
Ah, thanks! Didn't see that!

I'll try to publish everything tonight so we (and everyone else) are looking at the latest version.

Thanks!
